### ISSUE TITLE
Fails to use v3 in Next.js

### ISSUE THREAD

**Issue by IzumiSy** [badgateway/oauth2-client#180]
I confirmed that this package is working fine until v2.4.2, but the latest v3.0.0 causes Next.js to fail in building with this error.

<img width="969" alt="Image" src="https://github.com/user-attachments/assets/cd45dbc9-c795-4723-9128-807d5b81c020" />

**Comment by evert** [comment]
Interesting. I wonder if this has to do with the change to ESM.

How exactly are you importing this? We don't explicitly refer to the `.gz` so some magic is already happening.

**Comment by IzumiSy** [comment]
Let me share repro link on Stackblitz. Wait a moment.

**Comment by debater-coder** [comment]
I'm experiencing a similar issue in Vite 6. Repro link: https://stackblitz.com/edit/vitejs-vite-orumpa5y?file=src%2Fmain.js

```
11:06:19 pm [vite] (client) error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/@badgateway/oauth2-client/browser/oauth2-client.min.js:1:1306: ERROR: No loader is configured for ".gz" files: node_modules/@badgateway/oauth2-client/browser/oauth2-client.min.js.gz
node_modules/@badgateway/oauth2-client/browser/oauth2-client.min.js:1:1306: ERROR: No loader is configured for ".map" files: node_modules/@badgateway/oauth2-client/browser/oauth2-client.min.js.map
    at failureErrorWithLog (/home/projects/vitejs-vite-orumpa5y/node_modules/esbuild/lib/main.js:1467:15)
    at <anonymous> (/home/projects/vitejs-vite-orumpa5y/node_modules/esbuild/lib/main.js:936:44)
    at <anonymous> (/home/projects/vitejs-vite-orumpa5y/node_modules/esbuild/lib/main.js:1345:13)
```

**Comment by m-idler** [comment]
I got the same issue like @debater-coder using `Node.js v22.14.0`. With the latest v2 it seems to work without the mentioned issue.

**Comment by evert** [comment]
Thanks for the stackblitz link, it made it super easy to look into! I looked into this, and decided it's not worth trying to get Webpack to work with this. Instead, I intend to switch to vite for this package.

I released a dev version of this package, can you install it and see if it works for you?

```
npm i @badgateway/oauth2-client@3.2.0-dev0
```

It resolves the error for me, but it would be nice to get some more eyes on this. If it looks good, I'll release this.

**Comment by m-idler** [comment]
👍 for me it works using vite 6.2 / node 22 - thank you for the quick fix

**Comment by debater-coder** [comment]
The new release works for me too. vite 6.3, node 22.

**Comment by IzumiSy** [comment]
Thanks for everyone. Feel free to close this issue once the release is shipped.
